version: "3"
services:
    client:
        image: nowgnas/agora:client
        container_name: client
        ports:
            - 3000:3000
        environment:
            REACT_APP_SERVER_BASE_URL: baseurl
        networks:
            - AGORA
    backend:
        image: nowgnas/agora:backend
        container_name: backend
        ports:
            - 8081:8081
        environment:
            USE_PROFILE: prod
            HOST_NAME: a705agora
            SCHEMA: basetable
            USERNAME: root
            PASSWORD: dkrhfk705
            JWT_SECRET: lskjflsakjflakdjflk
            REDISHOST: redis
            REDISPASS: reidsa08a705
            MEETING_HOST: https://viduagora.duckdns.org
            MEETING_SECRET: ssafy705
        networks:
            - AGORA
networks:
    AGORA:
        external:
            name: AGORA
